server:
  port: 8097  # Servis sunucusunun portu


spring:
 application:
  name: config
 profiles: 
  active:
   - native
  
eureka:
 instance:
  hostname: localhost
 client:
   service-url:
    defaultZone: http://eureka-server-hostname:8097/eureka/
    
